name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: GopherParrot
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push snake animation to output branch
        uses: actions/checkout@v4
        with:
          ref: output
      - run: git add dist/github-contribution-grid-snake.svg
      # (add other necessary steps)
