name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: platane/snk@v3
        with:
          github_user_name: GopherParrot # Make sure this is YOUR GitHub username!
          outputs: |
            dist/github-snake.svg
      - name: Push to GitHub
        uses: git-auto-commit-action@v5
        with:
          commit_message: "Generate Snake Contribution"
          branch: main
